walker2d-v1-ppo:
    env: Walker2d-v2
    local_dir: './data/walker2d-v1/'
    run: PPO
    config:
        kl_coeff: 1.0
        num_sgd_iter: 20
        lr: .0001
        sgd_minibatch_size: 8192 #32768/4
        train_batch_size: 80000 #320000/4
        num_workers: 8
        num_gpus: 1
        batch_mode: complete_episodes
        observation_filter: MeanStdFilter

